---
framework: jest
preRun:
     command:
        - yarn install --dev
preMerge:
  pattern:
    - "./tests/integration/__tests__/*.js"
postMerge: 
  pattern: 
    - "./tests/integration/__tests__/*.js"
postRun:
     command:
        - yarn --version
version: 1.0
